name: howle
description: "howler.js binding with dart:js_interop"
version: 0.1.0
homepage: "https://github.com/ShuttleSpace/howle"

environment:
  sdk: ^3.3.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0