name: howle
description: "howler.js dart binding with dart:js_interop"
version: 0.1.2
homepage: "https://github.com/ShuttleSpace/howle"
repository: "https://github.com/ShuttleSpace/howle"
issue_tracker: "https://github.com/ShuttleSpace/howle/issues"
publish_to: https://pub.dartlang.org
platforms:
  web:
topics: 
  - audio
  - media
  - howler

environment:
  sdk: ^3.3.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  web: ^1.1.0